apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: go-epseevxp
  janus-idp.io/tekton: go-epseevxp
  backstage.io/kubernetes-id: go-epseevxp
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: go-epseevxp
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
